### ISSUE TITLE
Import error in openai-agents==0.2.10

### ISSUE THREAD

**Issue by AnujF1005** [openai/openai-agents-python#1640]
After updating to openai-agents sdk to 0.2.10, I am getting following error:
```
File "src\main.py", line 4, in <module>
 line 6, in <module>
    from agents import (
    Agent, Runner, set_default_openai_key,
    ModelSettings, RunResultStreaming, trace, InputGuardrailTripwireTriggered,
    OutputGuardrailTripwireTriggered,
)
  File "envl\Lib\site-packages\agents\__init__.py", line 8, in <module>
    from .agent import (
  File "env\Lib\site-packages\agents\agent.py", line 18, in <module>
    from .mcp import MCPUtil
  File "envl\Lib\site-packages\agents\mcp\__init__.py", line 14, in <module>
    from .util import (
  File "env\Lib\site-packages\agents\mcp\util.py", line 13, in <module>
    from ..tool import FunctionTool, Tool
  File "env\Lib\site-packages\agents\tool.py", line 15, in <module>
    from openai.types.responses.tool import WebSearchToolFilters
ImportError: cannot import name 'WebSearchToolFilters' from 'openai.types.responses.tool'
```
Python Version=3.11.13

**Comment by AJV009** [comment]
I have the same error

**Comment by colesmcintosh** [comment]
+1

**Comment by colesmcintosh** [comment]
Downgrading to 0.2.9 solves for now

**Comment by jgerstle136** [comment]
I opened up similar issue in the openai-python repo here, but probably belongs as an issue in this repo:
https://github.com/openai/openai-python/issues/2603

**Comment by jgerstle136** [comment]
Issue is broken compatibility with openai==1.104.1 ; downgrading to 1.102.0 seems to fix.
