### ISSUE TITLE
ImportError: cannot import name 'Reasoning' from 'openai.types.responses.response_output_item'

### ISSUE THREAD

**Issue by jfduque** [openai/openai-agents-python#30]
```python3
openai==1.66.2
openai-agents==0.0.2
```

https://github.com/openai/openai-agents-python/blob/96dd7921462b06535804d0f4caffaf69cd725ebf/src/agents/items.py#L22

I get this when trying sample code in https://openai.github.io/openai-agents-python/quickstart/

```python3
Traceback (most recent call last):
  File "/tmp/agent.py", line 1, in <module>
    from agents import Agent, InputGuardrail, GuardrailFunctionOutput, Runner
  File "/tmp/venv/lib/python3.13/site-packages/agents/__init__.py", line 8, in <module>
    from .agent import Agent
  File "/tmp/venv/lib/python3.13/site-packages/agents/agent.py", line 11, in <module>
    from .guardrail import InputGuardrail, OutputGuardrail
  File "/tmp/venv/lib/python3.13/site-packages/agents/guardrail.py", line 12, in <module>
    from .items import TResponseInputItem
  File "/tmp/venv/lib/python3.13/site-packages/agents/items.py", line 22, in <module>
    from openai.types.responses.response_output_item import Reasoning
ImportError: cannot import name 'Reasoning' from 'openai.types.responses.response_output_item' (/tmp/venv/lib/python3.13/site-packages/openai/types/responses/response_output_item.py)
```

**Comment by rm-openai** [comment]
Pushing an update shortly.

**Comment by rm-openai** [comment]
v0.0.3 now works with 1openai 1.66.2
