### ISSUE TITLE
ImportError: cannot import name 'MCPServerSse' from 'agents.mcp'

### ISSUE THREAD

**Issue by oms0401** [openai/openai-agents-python#413]
Traceback (most recent call last):
File "C:\Users\Lenovo\Desktop\Strats AI\open ai sdk\main.py", line 4, in
from agents.mcp import MCPServerSse, MCPServerStdio
ImportError: cannot import name 'MCPServerSse' from 'agents.mcp' (C:\Users\Lenovo\Desktop\Strats AI\open ai sdk\venv\Lib\site-packages\agents\mcp_init_.py)

This is the error i am facing despite creating the venv and installing the latest version of the open ai sdk

**Comment by rm-openai** [comment]
Are you on Python 3.9? Can you post the full error/stack trace?

**Comment by smortezah** [comment]
Same for Python 3.12.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from agents.mcp import MCPServerStdio
      2 samples_dir='.'
      4 async with MCPServerStdio(
      5     params={
      6         "command": "npx",
      7         "args": ["-y", "@modelcontextprotocol/server-filesystem", samples_dir],
      8     }
      9 ) as server:

ImportError: cannot import name 'MCPServerStdio' from 'agents.mcp' (.venv/lib/python3.12/site-packages/agents/mcp/__init__.py)
```

**Comment by limingyang325** [comment]
> Are you on Python 3.9? Can you post the full error/stack trace?
I am using Python 3.9, and I encountered the same issue.

**Comment by rm-openai** [comment]
Can you try `from agents.mcp.server import MCPServerSse` and tell me what error you see?

Also this wont work on Python 3.9, as MCP support requires 3.10+

**Comment by smortezah** [comment]
> Can you try `from agents.mcp.server import MCPServerSse` and tell me what error you see?

Not working.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from agents.mcp.server import MCPServerSse

File ~/.venv/lib/python3.12/site-packages/agents/mcp/server.py:10
      7 from typing import Any, Literal
      9 from anyio.streams.memory import MemoryObjectReceiveStream, MemoryObjectSendStream
---> 10 from mcp import ClientSession, StdioServerParameters, Tool as MCPTool, stdio_client
     11 from mcp.client.sse import sse_client
     12 from mcp.types import CallToolResult, JSONRPCMessage

File ~/mcp.py:6
      3 import shutil
      5 from agents import Agent, Runner
----> 6 from agents.mcp import MCPServer, MCPServerStdio
      9 async def run(mcp_server: MCPServer):
     10     agent = Agent(
     11         name="Assistant",
     12         instructions="Use the tools to read the filesystem and answer questions based on those files.",
     13         mcp_servers=[mcp_server],
     14     )

ImportError: cannot import name 'MCPServer' from 'agents.mcp' (.venv/lib/python3.12/site-packages/agents/mcp/__init__.py)
```

**Comment by rm-openai** [comment]
@smortezah thanks for bearing with me - can you try running this and telling me what you see?
```
import importlib.metadata
import os
import sys

print(sys.version)
try:
    print(importlib.metadata.version("agents"))
except Exception:
    print("-1")

try:
    import mcp

    print(dir(mcp))
except Exception:
    print("mcp not found")

agents_dir = importlib.import_module("agents").__path__[0]
print(str(agents_dir))


mcp_file = os.path.join(str(agents_dir), "mcp", "__init__.py")
with open(mcp_file) as f:
    print(f.read())
```

**Comment by smortezah** [comment]
```
3.12.9 (main, Feb  5 2025, 18:58:23) [Clang 19.1.6 ]
-1
mcp not found
~/.venv/lib/python3.12/site-packages/agents
try:
    from .server import (
        MCPServer,
        MCPServerSse,
        MCPServerSseParams,
        MCPServerStdio,
        MCPServerStdioParams,
    )
except ImportError:
    pass

from .util import MCPUtil

__all__ = [
    "MCPServer",
    "MCPServerSse",
    "MCPServerSseParams",
    "MCPServerStdio",
    "MCPServerStdioParams",
    "MCPUtil",
]
```

**Comment by rm-openai** [comment]
@smortezah How did you install the `openai-agents` package? Seems like somehow the MCP dep didnt get pulled in.

Can you also try
```
import importlib.metadata
print(importlib.metadata.version("openai-agents")
```

and reinstalling the package via
```
pip uninstall openai-agents
pip install openai-agents
```

**Comment by smortezah** [comment]
@rm-openai I installed it with `uv add "openai-agents[viz]"`.

```
import importlib.metadata
print(importlib.metadata.version("openai-agents")
```
0.0.7

Also, none of the followings worked:
```
uv remove "openai-agents[viz]"
uv add "openai-agents[viz]"
```
and
```
uv remove openai-agents
uv add openai-agents
```

HOWEVER, it works when I use `pip` instead of `uv`:
```
brew install python@3.12
python3.12 -m venv venv3.12
source venv3.12/bin/activate
pip install openai-agents

python -c "from agents.mcp.server import MCPServerSse"
```

**Comment by rm-openai** [comment]
@smortezah it sounds like you might not be using `uv run` when you install via uv. This worked fine for me:

```
mkdir test_mcp && cd test_mcp && uv init .

uv add "openai-agents[viz]" && uv run python -c "from agents.mcp.server import MCPServerSse"
```

**Comment by smortezah** [comment]
@rm-openai I guess I found the source of issue. If I put a python file that only includes `from agents.mcp.server import MCPServerSse` in the root directory of my project, it works. However, if I put this file in a subdirectory, it stops working regardless of where I call this file from; that is, whether I run `python a.py` or `uv run a.py` from the root directory or from within the subdirectory, it throws the error.

**Comment by smortezah** [comment]
@rm-openai @oms0401 Solved.

I encountered an interesting situation where I had a file named `mcp.py` in my subdirectory. Attempting to import `from mcp` resulted in a circular import. Interestingly, I wasn’t importing from `mcp` in my Jupyter notebook or the Python file I was trying to execute. However, the presence of `mcp.py` in the directory led to the following error:
`ImportError: cannot import name ‘MCPServer’ from ‘agents.mcp’ (.venv/lib/python3.12/site-packages/agents/mcp/__init__.py)`

To resolve this issue, I simply renamed `mcp.py`.

**Comment by rm-openai** [comment]
Wow that is kinda crazy. Makes sense though.

**Comment by oms0401** [comment]
Yes the issue is solved right now but the sdk is not stable in the current python 3.12 versio

**Comment by ycjcl868** [comment]
Same for Python 3.12.

**Comment by benjaminbascary** [comment]
any news on this? im still having the same error on python 3.11
